# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [24]:
import numpy as np
# formula = weight / (height**2) * 730

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi_results = weight / (height**2) * 730
print(bmi_results)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [41]:
def createMatrix():
    n1 = int(input('What number would you like to start with? '))
    n2 = int(input('What number would you like to end with? '))
    r = int(input('How many rows do you want? '))
    c = int(input('How many columns do you want? '))
    dT = input("What data type would you like?\n1) Float\n2) Integer")
    
    random_matrix = np.random.uniform(n1, n2, (r, c))
    
    if dT == 1:
        float_matrix = random_matrix.astype(np.float32)
        print(float_matrix)
    else:
        int_matrix = random_matrix.astype(np.int32)
        print(int_matrix)

createMatrix()


What number would you like to start with? 1
What number would you like to end with? 25
How many rows do you want? 5
How many columns do you want? 5
What data type would you like?
1) Float
2) Integer2
[[ 9  4  2  5  8]
 [ 7 20 11  1 16]
 [18  5 15 23 17]
 [21  4  4 10  6]
 [11 13 12 22  6]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [48]:
import csv
import numpy as np

def load_2017_data(filename, d = ','):
    data2017 = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                            usecols = np.arange(0,24), invalid_raise = False,
                            names = FIELDS, dtype = DATATYPES)
    
    return data2017

def load_2018_data(filename, d = ','):
    data2018 = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                            usecols = np.arange(0,24), invalid_raise = False,
                            names = FIELDS, dtype = DATATYPES)
    
    return data2018

In [59]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
bs2017 = load_2017_data('../numpy/redsox_2017_hitting.txt')
bs2018 = load_2018_data('../numpy/redsox_2018_hitting.txt')

slg2017 = np.array(bs2017['SLG'])
slg2018 = np.array(bs2018['SLG'])

slg2017_avg = sum(slg2017) / len(slg2017)
slg2018_avg = sum(slg2018) / len(slg2018)

print(f'2017 Average SLG: {slg2017_avg} vs 2018 Average SLG: {slg2018_avg}')

2017 Average SLG: 0.39334782374941785 vs 2018 Average SLG: 0.38750000335276125
